asp16/asp16/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace asp16.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

asp16/asp16/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace asp16.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

asp16/asp16/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace asp16.Controllers
{
    public class ServicosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

asp16/asp16/Views/Shared/Cabecalho.cshtml
<div class="container-fluid Cabecalho p-3">
    @*Colocamos <a> e inserimos os comandos abaixo para informando primeiro o controller e depois a pagina inicial*@
    <h1><a asp-controller="home" asp-action="index"><i class="fa fa-home pr-3"></i></a>@ViewBag.nome_empresa</h1> 
    
</div>

asp16/asp16/Views/Shared/Layout/_Layout.cshtml
@{
    ViewData["nome_empresa"] = "A minha empresa";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.nome_empresa</title>

    @*Colamos o bootstrap abaixo de title em head*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/main.css" rel="stylesheet" />

</head>
<body>
    @*falta criar as partial view de Navegacao, Rodape*@

    @Html.Partial("Cabecalho")
    @Html.Partial("Navegacao")

    @RenderBody()

    @Html.Partial("Rodape")

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

asp16/asp16/Views/Shared/Navegacao.cshtml
<div class="container-fluid Navegacao p-3 text-right">
    @*Text-right define o alinhamento para a esquerda*@
    @*Criando as hiper ligações entre as paginas que ira apontar primeiro para um controlador e em seguida realizar um ação*@
    <a asp-controller="Home" asp-action="index">Início</a>| @*Foi colocado um separador manualmente*@
    <a asp-controller="Servicos" asp-action="index">Serviços</a>|
    <a asp-controller="Contato" asp-action="index">Contato</a>

</div>

asp16/asp16/Views/Shared/Rodape.cshtml
<div class="container-fluid Rodape p-3 text-center">
    <p>@ViewBag.nome_empresa &copy; @DateTime.Now.Year</p>
    <div class="Sociais" icon-center>
        @*  Na estrutura a abaixo podemos através do link criado acessarmos as redes socias *@
        <a href="https://wwww.facebook.com"><i class="fa fa-facebook"></i></a>
        <a href="https://wwww.twitter.com"><i class="fa fa-twitter"></i></a>
        <a href="https://wwww.instagram.com"><i class="fa fa-instagram" > </i></a>
    </div>
</div>